"""Initial migration with activities table

Revision ID: 213dcef54d98
Revises: 
Create Date: 2025-04-15 16:10:08.711882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213dcef54d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('c_id', sa.CHAR(length=8), nullable=False),
    sa.Column('c_usename', sa.CHAR(length=20), nullable=False),
    sa.Column('c_password', sa.CHAR(length=10), nullable=False),
    sa.Column('c_phonenumber', sa.CHAR(length=13), nullable=True),
    sa.Column('c_score', sa.CHAR(length=5), nullable=True),
    sa.Column('c_avatar_URL', sa.CHAR(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.CHAR(length=8), nullable=False),
    sa.Column('tag_name', sa.CHAR(length=20), nullable=False),
    sa.Column('tag_desc', sa.CHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activities',
    sa.Column('a_id', sa.CHAR(length=8), nullable=False),
    sa.Column('a_name', sa.CHAR(length=255), nullable=False),
    sa.Column('a_text', sa.Text(), nullable=True),
    sa.Column('a_image_url', sa.CHAR(length=255), nullable=True),
    sa.Column('a_location', sa.Text(), nullable=True),
    sa.Column('creator_c_id', sa.CHAR(length=8), nullable=True),
    sa.Column('limit_p', sa.Integer(), nullable=True),
    sa.Column('activity_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_c_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_relationships',
    sa.Column('user_id1', sa.CHAR(length=8), nullable=False),
    sa.Column('user_id2', sa.CHAR(length=8), nullable=False),
    sa.Column('relationship_status', sa.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id1'], ['client.c_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('user_id1', 'user_id2')
    )
    op.create_table('groups',
    sa.Column('g_id', sa.CHAR(length=8), nullable=False),
    sa.Column('g_name', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.CHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('hobby',
    sa.Column('c_id', sa.CHAR(length=8), nullable=False),
    sa.Column('tag_id', sa.CHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['client.c_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('c_id', 'tag_id')
    )
    op.create_table('activity_participation',
    sa.Column('a_id', sa.CHAR(length=8), nullable=False),
    sa.Column('participant_c_id', sa.CHAR(length=8), nullable=False),
    sa.Column('creator_c_id', sa.CHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['activities.a_id'], ),
    sa.ForeignKeyConstraint(['creator_c_id'], ['client.c_id'], ),
    sa.ForeignKeyConstraint(['participant_c_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('a_id', 'participant_c_id')
    )
    op.create_table('activity_tag_association',
    sa.Column('a_id', sa.CHAR(length=8), nullable=False),
    sa.Column('tag_id', sa.CHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['a_id'], ['activities.a_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('a_id', 'tag_id')
    )
    op.create_table('chat_records',
    sa.Column('message_id', sa.CHAR(length=8), nullable=False),
    sa.Column('sender_c_id', sa.CHAR(length=8), nullable=True),
    sa.Column('receiver_c_id', sa.CHAR(length=8), nullable=True),
    sa.Column('message_content', sa.CHAR(length=255), nullable=True),
    sa.Column('send_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('activity_id', sa.CHAR(length=8), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.a_id'], ),
    sa.ForeignKeyConstraint(['receiver_c_id'], ['client.c_id'], ),
    sa.ForeignKeyConstraint(['sender_c_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('evaluations',
    sa.Column('e_id', sa.CHAR(length=8), nullable=False),
    sa.Column('user_id', sa.CHAR(length=8), nullable=False),
    sa.Column('a_id', sa.CHAR(length=8), nullable=True),
    sa.Column('evaluation_content', sa.CHAR(length=255), nullable=True),
    sa.Column('e_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('e_type', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['a_id'], ['activities.a_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('e_id')
    )
    op.create_table('group_members',
    sa.Column('m_id', sa.CHAR(length=8), nullable=False),
    sa.Column('g_id', sa.CHAR(length=8), nullable=True),
    sa.Column('c_id', sa.CHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['client.c_id'], ),
    sa.ForeignKeyConstraint(['g_id'], ['groups.g_id'], ),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.create_table('group_records',
    sa.Column('message_id', sa.CHAR(length=8), nullable=False),
    sa.Column('sender_c_id', sa.CHAR(length=8), nullable=True),
    sa.Column('g_id', sa.CHAR(length=8), nullable=True),
    sa.Column('chat_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('chat_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['groups.g_id'], ),
    sa.ForeignKeyConstraint(['sender_c_id'], ['client.c_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('message')
    op.drop_table('group_records')
    op.drop_table('group_members')
    op.drop_table('evaluations')
    op.drop_table('chat_records')
    op.drop_table('activity_tag_association')
    op.drop_table('activity_participation')
    op.drop_table('hobby')
    op.drop_table('groups')
    op.drop_table('friend_relationships')
    op.drop_table('activity')
    op.drop_table('activities')
    op.drop_table('user')
    op.drop_table('tags')
    op.drop_table('client')
    # ### end Alembic commands ###
